---
- hosts: all
  become: true
  vars_files:
    - vars/default.yml

  roles:
    - locale
    - do-agent
    - apt-upgrade
    - users
    - copy-developer-keys
    - install-docker
    - docker-permission
